// Generated by Selenium IDE
package firstpackage;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FacebookTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void facebook() {
    driver.get("https://www.google.com/search?q=facebook&sca_esv=557753954&sxsrf=AB5stBgpiXSvKWT9emLWY7ts8COg0LWZ0A%3A1692268138164&source=hp&ei=avbdZMS8B9eC2roPn7-DUA&iflsig=AD69kcEAAAAAZN4EehveihfoWk77_5HVS3YBC4Ml60ku&ved=0ahUKEwjEmfOJvuOAAxVXgVYBHZ_fAAoQ4dUDCAk&uact=5&oq=facebook&gs_lp=Egdnd3Mtd2l6IghmYWNlYm9vazIHECMYigUYJzIHECMYigUYJzIHECMYigUYJzIUEC4YigUYsQMYgwEYxwEY0QMYkQIyCBAAGIoFGJECMgcQABiKBRhDMgsQABiABBixAxiDATIHEAAYigUYQzIHEAAYigUYQzINEAAYigUYsQMYgwEYQ0jjIlAAWI0UcAB4AJABAJgBowKgAcIIqgEFMS42LjG4AQPIAQD4AQHCAhMQLhiKBRixAxiDARjHARjRAxhDwgIREC4YgAQYsQMYgwEYxwEY0QPCAgsQABiKBRixAxiDAcICBxAuGIoFGEPCAggQABiABBixAw&sclient=gws-wiz");
    driver.close();
    driver.findElement(By.cssSelector(".eKjLze .LC20lb")).click();
  }
}
